<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateExpenseDescriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('expense_descriptions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('category');
            $table->string('description');
            $table->integer('state')->default('1');
            $table->timestamps();
        });

        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Prev Plan 15'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bateria'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Instalacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Filtro Aire'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Filtro Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Shell Helix'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Administracion Octubre 2018'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Cambio Filtro'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bombillos'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Juego Pastilas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Mano de Obra'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Guardapolvo'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Kit Embrague'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Subscripcion'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Gas'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Puntas ejes'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Manija'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Kit Clutch Atos'));
        DB::table('expense_descriptions')->insert(array('category'=>'12', 'description'=>'Rodamiento'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Encendedor'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Cambio Equipo de gas'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Emulador'));
        DB::table('expense_descriptions')->insert(array('category'=>'28', 'description'=>'Alineacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bujias'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Servicio Scanner'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Halogeno'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Cuadrar Minima'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Llantas (2)'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Ajuste Emulador'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Pila Bomba Gas'));
        DB::table('expense_descriptions')->insert(array('category'=>'14', 'description'=>'SOAT'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'BZM 1509'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Escobillas'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bujes Arranque'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Switch Interruptor Bomba Gasolina'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Juego Bandas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Cambio de Bandas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Rectificacion de Campanas'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Llave duplicado'));
        DB::table('expense_descriptions')->insert(array('category'=>'16', 'description'=>'Revision Tecnomecanica'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaquetadura Motor'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Pera Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Pera Temperatura'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Correa Reparticion'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Tensor Correa'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Silicona'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Correa Alternador'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Bomba Agua'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Manguera Bomba Agua'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Manguera Calefaccion'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Casquetes Biela Bancada'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Media Lunas std'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Valvulas Admision y Escape'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Sellos Valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Anillos'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Soporte Motor Trasero'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Termostato'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Bomba Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Manguera Booster'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaque Tapa Valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Abrazaderas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Mangueras Agua'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Guias Valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Juego Pistones'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Aceite y Filtros'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Lavado Inyectores'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Rectificar Bloque'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Rectificar Cigueñal'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Rectificar Culatas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Ensamblar Pistones'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Sentar y Armar Valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Lavar Motor'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Circulo de Bancada Biela'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Carcaza'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Fusible'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Bandas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Bocin Trasero'));
        DB::table('expense_descriptions')->insert(array('category'=>'21', 'description'=>'Caja de direccion GTI completa'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Puños (2)'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Axial'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Tornillo'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Reten Toma'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Gasolina'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Punta L/R Atos lado conductor'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Gasto Gasolina Corrient Oxigenada'));
        DB::table('expense_descriptions')->insert(array('category'=>'18', 'description'=>'Traspaso'));
        DB::table('expense_descriptions')->insert(array('category'=>'22', 'description'=>'Instalacion Pila Gasolina'));
        DB::table('expense_descriptions')->insert(array('category'=>'22', 'description'=>'Pila Gasolina'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Instalacion de Alta PCY'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Revision Annual'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Combustible'));
        DB::table('expense_descriptions')->insert(array('category'=>'3', 'description'=>'Seguro Extracontractual'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bobina'));
        DB::table('expense_descriptions')->insert(array('category'=>'30', 'description'=>'Revision'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Ventilador Radiador'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Administracion Noviembre 2018 - Enero 2019'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Pastillas'));
        DB::table('expense_descriptions')->insert(array('category'=>'25', 'description'=>'Tapa y Empaque radiador'));
        DB::table('expense_descriptions')->insert(array('category'=>'25', 'description'=>'Motor y Ventilador'));
        DB::table('expense_descriptions')->insert(array('category'=>'25', 'description'=>'Tapa Radiador'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Rectificacion Bases y Valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Cambio Guias'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Armadas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaque Culata'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaque Multiple Admision'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Reten Eje de Levas'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Rotacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Libre'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Desbarada'));
        DB::table('expense_descriptions')->insert(array('category'=>'12', 'description'=>'Tramite'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Revision Preventiva'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Fotocopias'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Tarjetas de Control'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Autenticacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Parqueo'));
        DB::table('expense_descriptions')->insert(array('category'=>'20', 'description'=>'Patios'));
        DB::table('expense_descriptions')->insert(array('category'=>'12', 'description'=>'Febrero & Marzo 2019'));
        DB::table('expense_descriptions')->insert(array('category'=>'12', 'description'=>'Tarjeta de Operacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'30', 'description'=>'Reparacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bombillos Stop'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Mantenimiento Chapa'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Llanta'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Laminacion Tarjeton'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Planilla de Viaje'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Valvula IAC'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Rotula'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Axiales (2)'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Muñecos'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Inyector'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Elevador'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Bujes Palanca Cambios'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Manguera Desague'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Revision Alternador'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Revision arranque'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Cambio Bujes'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Montaje'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Juego Bujes Cuña Arandelas'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Bujes Puño'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Soporte Palanca de Cambios'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Buje Soporte Motor'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Tornillos'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Reforzar y Soldar Cuña'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Sello'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Sensor Velocidad'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Administracion Abril 2019'));
        DB::table('expense_descriptions')->insert(array('category'=>'27', 'description'=>'Seguridad Social'));
        DB::table('expense_descriptions')->insert(array('category'=>'23', 'description'=>'Impuestos'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Yukkazzo'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Cambio de Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Calibracion'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Instalacion de Alta'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Punta L/R'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Amortiguador'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Bombillo'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Pin de Eje'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Punta L/C'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Bocin delantero'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Abrazadora'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Pin cacho'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Guaya Acelerador'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Ace'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Bloque Tapones'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Probar Bancada y Biela'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Lavado'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Culata de Atos, alternador y multiple'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Asco gasolina'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Probar Inyectores'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Electrico pacha'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Cambio Flexible'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Calibracion Analizador'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Pistones'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Camisas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaquetura del motor'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Kit Reparacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Erosol Negro'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Filtro Aceite y Aire'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Inyectores'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Mantenimiento Aceleracion'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Mantenimiento Frenos'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Empaquetura valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Kit Reparacion correa'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Manguera 30 cm'));
        DB::table('expense_descriptions')->insert(array('category'=>'26', 'description'=>'Soldadura'));
        DB::table('expense_descriptions')->insert(array('category'=>'26', 'description'=>'Cambio anillo'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Conectores'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Analisis de gases'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Campanas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Graduacion frenos'));
        DB::table('expense_descriptions')->insert(array('category'=>'29', 'description'=>'Revi'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Cilindro'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Sensor de Oxigeno'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Scannear'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Calibrada valvulas'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Administracion'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Vulcanuzacion'));
        DB::table('expense_descriptions')->insert(array('category'=>'17', 'description'=>'Puerta remplazo'));
        DB::table('expense_descriptions')->insert(array('category'=>'21', 'description'=>'Caja'));
        DB::table('expense_descriptions')->insert(array('category'=>'21', 'description'=>'Valvulina'));
        DB::table('expense_descriptions')->insert(array('category'=>'21', 'description'=>'Retenedor'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Balanceo'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Eje Izquierdo'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'2 Libras de Grasa'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'8 Abrazaderas Plasticas'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Cauchos para estabilizadora'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Kit de Clutch'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Reten Volante'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'2 Cuartos de Valvulina'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'2 Abrazaderas aceradas'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Suavizador'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Guaya Clutch'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Pernos con Tuercas'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Hidrostatica CO2'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Contenedor'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Reten Piñon velocimetro'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Pinta liquido de Freno'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Empaque'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Juego Plumillas'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Legalizacion Regulador'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Pluma Metalica'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Aspirales Reforzados'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Amortiguadores'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Mogollas'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Liquido'));
        DB::table('expense_descriptions')->insert(array('category'=>'26', 'description'=>'Alquiler catalizador'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Revision Inyeccion'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Espirales'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Miscelaneo'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Teja ventana'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bombillo Techo'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Piñones'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Kiy bujes barra de cambios'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Murcielagos'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Tuercas y esparragos'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Cuarto de Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Escaniada'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Duplicado'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Calcomanias'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Papel humedo'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Manijas'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Automatico de Arranque'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Switch Ignicion'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Pera Agua'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Correa'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Buje Guaya'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Empaque Exhosto'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Eje Levas'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Romula Daewoo'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Rosca Helice'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Kit Repaticion'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Grasa Clutch'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Revision Hidrostatica'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Cambio pera'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Manguera '));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Pachas'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Poder'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Pujo'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Rodamientos'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Sonda Lambda'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Tijera'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Piñon Velocimetro'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Topes'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Kit bujes'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Cables'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Coraza'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Pin'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Grua'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Arreglo Farola'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Switch parqueo'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Flasher'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Bajado de arranque'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Conector de Pacha'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Tapa Termostato'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Terminal'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Pera Reverso'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Rodamientos (2)'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Tapetes'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Soporte Amortiguador'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Pacha'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Retencion Control Cambios'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Pera de reverso'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Bocin'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Switch'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Instalacion Yukazo'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Reten Polea'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Sensor de Minima'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Ajuste Manguera'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Buje Tijera'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Placa Lateral'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Reten Aceite'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Liga'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Manguera Codo'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Reten Eje'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Tubo trasero termostato'));
        DB::table('expense_descriptions')->insert(array('category'=>'1', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'2', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'3', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'4', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'5', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'6', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'7', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'8', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'9', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'10', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'11', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'12', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'13', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'14', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'15', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'16', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'17', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'18', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'19', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'20', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'21', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'22', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'23', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'24', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'25', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'26', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'27', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'28', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'29', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'30', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'31', 'description'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('category'=>'32', 'description'=>'Otro Servicio'));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('expense_descriptions');
    }
}
